### ISSUE TITLE
Segment fault while running iser testing

### ISSUE THREAD

**Issue by clicx** [sahlberg/libiscsi#259]
[SKIPPED] REPORT_SUPPORTED_OPCODES is not implemented.
    [FAILED] PRIN command: failed with sense. SENSE KEY:ILLEGAL_REQUEST(5) ASCQ:INVALID_FIELD_IN_CDB(0x2400)

     CUnit - A unit testing framework for C - Version 2.1-2
     http://cunit.sourceforge.net/

Suite: CompareAndWrite
  Test: Simple ...    [SKIPPED] --dataloss flag is not set. Skipping test.
passed
  Test: DpoFua ...    [SKIPPED] --dataloss flag is not set. Skipping test.
passed
  Test: Miscompare ...    [SKIPPED] --dataloss flag is not set. Skipping test.
passed
  Test: Unwritten ...    [SKIPPED] --dataloss flag is not set. Skipping test.
passed
  Test: InvalidDataOutSize ...    [SKIPPED] --dataloss flag is not set. Skipping test.
passedSegmentation fault (core dumped)

on tgt is same.

**Comment by clicx** [comment]
#0  0x00007fe0bd23e30f in iser_reg_mr (iser_conn=0x14ef9c0) at iser.c:995
#1  iser_connected_handler (cma_id=<optimized out>) at iser.c:1241
#2  iser_cma_handler (event=0x7fe0b2ffce90, cma_id=<optimized out>, iser_conn=0x14ef9c0) at iser.c:1267
#3  cm_thread (arg=0x14ef9c0) at iser.c:1321
#4  0x00007fe0bc384e25 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fe0bcb1f34d in clone () from /lib64/libc.so.6

**Comment by sahlberg** [comment]
bug bankrupcy
