### ISSUE TITLE
Aborted with signal SIGABRT,  libiscsi master when enable iser on debian 12.7 with Linux (Alpine 3.20.3) guest

### ISSUE THREAD

**Issue by ir1ka** [sahlberg/libiscsi#430]
When using version master (commit: 551d90724d850874c6a094f71f07e7303eb9d590, with patch for compatable 1.19.0, see follow), the linux guest (Alpine 3.20.3), the crash reappeared. But  the windwos 10 guest is work fine.

Follow is the crash backtrace:
```gdb
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007efce438de9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007efce433efb2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007efce4329472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007efce4382430 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7efce449c459 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007efce43977ba in malloc_printerr (str=str@entry=0x7efce449f0c8 "free(): invalid next size (fast)") at ./malloc/malloc.c:5660
#6  0x00007efce439962a in _int_free (av=0x7efce44d5c60 <main_arena>, p=0x5615c060d640, have_lock=have_lock@entry=0) at ./malloc/malloc.c:4518
#7  0x00007efce439be9f in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3385
#8  0x00007efce3ca6171 in iscsi_free (ptr=<optimized out>, iscsi=0x5615c0594ad0) at init.c:108
#9  iscsi_free (iscsi=0x5615c0594ad0, ptr=<optimized out>) at init.c:106
#10 0x00007efce3cbaea5 in iscsi_iser_free_pdu (iscsi=0x5615c0594ad0, pdu=0x5615c02b1ae0) at iser.c:565
#11 0x00007efce3caab74 in iscsi_process_pdu (iscsi=iscsi@entry=0x5615c0594ad0, in=in@entry=0x7fff89d3c8d0) at pdu.c:739
#12 0x00007efce3cbb13d in iser_rcv_completion (iser_conn=<optimized out>, rx_desc=<optimized out>) at iser.c:1383
#13 iser_handle_wc (iser_conn=<optimized out>, wc=<optimized out>) at iser.c:1417
#14 cq_event_handler (iser_conn=iser_conn@entry=0x5615c0596450) at iser.c:1459
#15 0x00007efce3cbcb3f in cq_handle (iser_conn=0x5615c0596450) at iser.c:1507
#16 iscsi_iser_service (iscsi=0x5615c0594ad0, revents=<optimized out>) at iser.c:118
#17 0x00007efce3ccfaaf in ?? () from /usr/bin/../lib/x86_64-linux-gnu/qemu/block-iscsi.so
#18 0x00005615b1cb8778 in aio_dispatch_handler (ctx=ctx@entry=0x5615c0331ac0, node=0x5615c05cf810) at ../../util/aio-posix.c:369
#19 0x00005615b1cb9012 in aio_dispatch_handlers (ctx=0x5615c0331ac0) at ../../util/aio-posix.c:412
#20 aio_dispatch (ctx=0x5615c0331ac0) at ../../util/aio-posix.c:422
#21 0x00005615b1cccdde in aio_ctx_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../../util/async.c:352
#22 0x00007efce48dd7a9 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00005615b1ccf3d8 in glib_pollfds_poll () at ../../util/main-loop.c:297
#24 os_host_main_loop_wait (timeout=0) at ../../util/main-loop.c:320
#25 main_loop_wait (nonblocking=nonblocking@entry=0) at ../../util/main-loop.c:606
#26 0x00005615b192b957 in qemu_main_loop () at ../../softmmu/runstate.c:739
#27 0x00005615b1b4f956 in qemu_default_main () at ../../softmmu/main.c:37
#28 0x00007efce432a24a in __libc_start_call_main (main=main@entry=0x5615b175e570 <main>, argc=argc@entry=112, argv=argv@entry=0x7fff89d3cfc8) at ../sysdeps/nptl/libc_start_call_main.h:58
#29 0x00007efce432a305 in __libc_start_main_impl (main=0x5615b175e570 <main>, argc=112, argv=0x7fff89d3cfc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fff89d3cfb8) at ../csu/libc-start.c:360
#30 0x00005615b175fe51 in _start ()
```

Patch:
```diff
diff --git a/include/scsi-lowlevel.h b/include/scsi-lowlevel.h
index fe65daf..bdc2103 100644
--- a/include/scsi-lowlevel.h
+++ b/include/scsi-lowlevel.h
@@ -284,10 +284,8 @@ struct scsi_sense {
 	unsigned            sense_specific:1;
 	unsigned            ill_param_in_cdb:1;
 	unsigned            bit_pointer_valid:1;
-	unsigned            info_valid:1;
 	unsigned char       bit_pointer;
 	uint16_t            field_pointer;
-	uint64_t            information;
 };
 
 struct scsi_data {
diff --git a/lib/Makefile.am b/lib/Makefile.am
index ba6aaee..b2afcb8 100644
--- a/lib/Makefile.am
+++ b/lib/Makefile.am
@@ -45,7 +45,7 @@ endif
 
 EXTRA_libiscsi_la_DEPENDENCIES = libiscsi.syms
 
-SOCURRENT=10
+SOCURRENT=7
 SOREVISON=0
 SOAGE=0
 libiscsi_la_LDFLAGS = \
diff --git a/lib/iscsi-command.c b/lib/iscsi-command.c
index d218060..6e1eb0a 100644
--- a/lib/iscsi-command.c
+++ b/lib/iscsi-command.c
@@ -334,8 +334,7 @@ static void parse_sense_descriptors(struct scsi_sense *sense, const uint8_t *sb,
 		case 0:
 			/* Information descriptor with VALID flag */
 			if (addl_len == 0x0a && p[2] & 0x80) {
-				sense->info_valid = 1;
-				sense->information = scsi_get_uint64(p + 4);
+				scsi_get_uint64(p + 4);
 			}
 			break;
 		case 2:
@@ -356,8 +355,7 @@ void scsi_parse_sense_data(struct scsi_sense *sense, const uint8_t *sb)
 		/* Fixed format */
 		sense->key  = sb[2] & 0x0f;
 		if (sb[0] & 0x80) {	/* VALID */
-			sense->info_valid = 1;
-			sense->information = scsi_get_uint32(sb + 3);
+			scsi_get_uint32(sb + 3);
 		}
 		sense->ascq = scsi_get_uint16(&sb[12]);
 		parse_sense_spec(sense, sb + 15);
diff --git a/test-tool/test_compareandwrite_miscompare.c b/test-tool/test_compareandwrite_miscompare.c
index a8bdef3..20f233e 100644
--- a/test-tool/test_compareandwrite_miscompare.c
+++ b/test-tool/test_compareandwrite_miscompare.c
@@ -225,10 +225,10 @@ test_compareandwrite_miscompare_sense(void)
                 CU_ASSERT(tsk->sense.key == SCSI_SENSE_MISCOMPARE);
                 CU_ASSERT(tsk->sense.ascq
                                 == SCSI_SENSE_ASCQ_MISCOMPARE_DURING_VERIFY);
-                if (tsk->sense.info_valid) {
+                if (0) {
                         logging(LOG_VERBOSE, "Check Information field provided"
                                 " with miscompare sense response");
-                        CU_ASSERT_EQUAL(tsk->sense.information, i);
+                        CU_ASSERT_EQUAL(i, i);
                 }
 
                 scsi_free_scsi_task(tsk);
```

_Originally posted by @Ir1Ka in https://github.com/sahlberg/libiscsi/issues/277#issuecomment-2455188740_

**Comment by sahlberg** [comment]
Can it trigger under valgrind?

I don't have access to any iSER systems so :-(

**Comment by mjt0k** [comment]
This smalloc vs malloc seems to be a very poor interface, - it is just too easy to misuse smalloc/free vs malloc/sfree like this, it really is.  Either there should be single entry point for malloc and free, which decides to use small or regular allocator, remembers the allocation size somewhere near the data and the free routine calls the regular or small allocator too.  Or maybe not remembers, but free (single point) also requires the initial size - which is a bit more difficult to use but still better than now. Or, like almost all other systems out there does, have just one allocator and use it for all sizes.
